---
title: 'Stable Isotope Mixing Models: course timetable'
author: "Andrew Parnell and Andrew Jackson"
date: "June 2019"
output:
  html_document: default
  pdf_document: default
---

Course pre-requisites can be found [here](https://andrewcparnell.github.io/simms_course/Prerequisites.html). All the raw files and code can be found [here](https://github.com/andrewcparnell/simms_course). Click 'Clone or Download' near the top right and then 'Download ZIP' if you want an offline copy of everything. 

Here is a [simple script for getting started with ggplot](https://andrewcparnell.github.io/simms_course/ap_notes/gg_plot_class.R) which might be useful for some but is not compulsory. 

## Monday

Introduction to SIA data and revision of basic statistical and R concepts

Time  | Class
------------- | ----------------------------------------------------
9:30-10:30 | [Introduction: why use a SIMM? (AJ)](https://andrewcparnell.github.io/simms_course/aj-content/intro-why-use-a-SIMM.html)
10:30-10:45 | Coffee break
10:45-11:45 | [Revision of likelihood and regression (AP)](https://andrewcparnell.github.io/simms_course/ap_notes/revision_of_likelihood_regression/revision_of_likelihood_and_regression.pdf)
11:45-12:00 | Break 
12:00-12:45 | [Guided practical: Revision of important R concepts (AP)](https://andrewcparnell.github.io/simms_course/ap_notes/revision_of_R/Revision_of_R.R)
12:45-13:45 | Lunch
13:45-15:00 | [Guided practical: Intro to SI data](https://andrewcparnell.github.io/simms_course/aj-content/practicals/day-1-pm1/Exploring-Basic-SIA-Data.html) and [biplots](https://andrewcparnell.github.io/simms_course/aj-content/practicals/day-1-pm1/first-biplot.html) (AJ)
15:00-15:30 | Coffee break
15:30-17:00 | [Guided Practical: Simple linear models to explain SIA data](https://andrewcparnell.github.io/simms_course/aj-content/practicals/day-1-pm2/basic-SIA-linear-models.html) (AJ)

## Tuesday

Introduction to Bayes and SIMMs

Time  | Class
------------- | ----------------------------------------------------
9:30-10:30 | [An introduction to Bayesian statistics (AP)](https://andrewcparnell.github.io/simms_course/ap_notes/intro_bayes/intro_bayes.pdf)
10:30-10:45 | Coffee break
10:45-11:45 | [Guided practical: R, JAGS, and linear regression (AP)](https://andrewcparnell.github.io/simms_course/ap_notes/prac_jags/practical_R_jags_and_lr.R)
11:45-12:00 | Break 
12:00-12:45 | [Differences between regression models and SIMMs (AP)](https://andrewcparnell.github.io/simms_course/ap_notes/reg_and_simms/reg_and_simms.pdf) 
12:45-13:45 | Lunch
13:45-15:00 | [Guided practical: intro to simmr (AP)](https://andrewcparnell.github.io/simms_course/ap_notes/prac_using_simmr/simmr_vignette_code.R)
15:00-15:30 | Coffee break
15:30-17:00 | Practical: options are (1) run your data through AJ's plots from yesterday, or (2) get your data to run in simmr, or (3) go back and learn ggplot2 from [this script](https://andrewcparnell.github.io/simms_course/ap_notes/gg_plot_class.R)

## Wednesday

simmr / MixSIAR

Time  | Class
------------- | ----------------------------------------------------
9:30-10:30 | [Dos and don'ts of using mixing models with discussion (AJ)](https://andrewcparnell.github.io/simms_course/aj-content/siar-dos-and-donts.html)
10:30-10:45 | Coffee break
10:45-11:45 | Dos and don'ts continued (AJ)
11:45-12:00 | Break 
12:00-12:45 | [The statistical model behind simmr (and SIAR) (AP)](https://andrewcparnell.github.io/simms_course/ap_notes/siar_stats/siar_stats.pdf)
12:45-13:45 | Lunch
13:45-15:00 | Guided Practical: using [MixSIAR](https://andrewcparnell.github.io/simms_course/ap_notes/prac_mixsiar_and_jags/mixsiar_script.R) and [incorporating prior information in simmr (AP)](https://andrewcparnell.github.io/simms_course/ap_notes/prac_using_simmr/simmr_with_priors.R)
15:00-15:30 | Coffee break
15:30-17:00 | [Practical: pick a MixSIAR example](https://cran.r-project.org/web/packages/MixSIAR/vignettes/) and [look at the manual](https://github.com/brianstock/MixSIAR/blob/master/Manual/mixsiar_manual_3.1.pdf)


## Thursday 

Source grouping & SIBER

Time  | Class
------------- | ----------------------------------------------------
9:30-10:30 | [Practical: Source grouping, when and how? (AJ)](https://andrewcparnell.github.io/simms_course/aj-content/practicals/source-aggregation.html) 
10:30-10:45 | Coffee break
10:45-11:45 | [Creating and understanding Stable Isotope Bayesian Ellipses (SIBER) (AJ)](https://andrewcparnell.github.io/simms_course/aj-content/siber-intro-ellipses.html)
11:45-12:00 | Break 
12:00-12:45 | [Guided Practical: Using SIBER to compare populations using ellipses (AJ)](https://andrewcparnell.github.io/simms_course/aj-content/practicals/siber-comparing-populations.html)
12:45-13:45 | Lunch
13:45-15:00 | [Community level metrics using SIBER (AJ)](https://andrewcparnell.github.io/simms_course/aj-content/siber-intro-hulls.html)
15:00-15:30 | Coffee break
15:30-17:00 | [Guided Practical: Using SIBER to compare communities using convex hulls (AJ)](https://andrewcparnell.github.io/simms_course/aj-content/practicals/siber-comparing-communities.html)


## Friday

Bring Your Own Data!

Please sign up for a time slot with your name and a brief description of your question and we will meet with you and discuss potential solutions. https://docs.google.com/spreadsheets/d/15NYwk-qwjJRQeKi2yFzY9_7Xg8EsSexKoL_CfEzZ7K4/edit?usp=sharing


Time  | Class
------------- | ----------------------------------------------------
9:30-10:30 | [(optional practical)](https://andrewcparnell.github.io/simms_course/aj-content/practicals/Introduction-to-SIDER.html) [Estimating trophic discrimination factors using SIDER (AJ)](https://andrewcparnell.github.io/simms_course/aj-content/sider-intro.html) 
10:30-10:45 | Coffee break
10:45-11:45 | [(optional class) SIMMs for complex data sets: time series and mixed effects models (AP)](https://andrewcparnell.github.io/simms_course/ap_notes/complex_simms/complex_SIMMs.pdf)
11:45-12:00 | Break 
12:00-12:45 | [(Optional class) From simmr to MixSIAR (AP)](https://andrewcparnell.github.io/simms_course/ap_notes/siar_mixsiar/siar_mixsiar.pdf))
12:45-13:45 | Lunch
13:45-15:00 | BYOD
15:00-15:30 | Coffee break
15:30-17:00 | BYOD

