---
title: "Pre-requisites for Stable Isotope Mixing Models course"
author: "Andrew Parnell and Andrew Jackson"
output: html_document
---

In preparation for the course please install the following, preferably in the below suggested order. Make sure you run these before you arrive in case of poor (or crowded!) internet.

Remember you will need to bring your own personal computer for the duration of the course.

### Step 1

Install the following using the corresponding links

-	R: [http://www.r-project.org](http://www.r-project.org)

-	Rstudio (optional but recommended): [https://www.rstudio.com](https://www.rstudio.com)

-	JAGS: http://sourceforge.net/projects/mcmc-jags/files/

### Step 2

Now install all the pacakges required for the course by entering the following code in to R

```{r,eval=FALSE}
install.packages('rjags')
library(rjags)
install.packages('compositions')
library(compositions)
install.packages('devtools')
library(devtools) 
install_github("andrewljackson/siar") 
library(siar)
install_github("andrewcparnell/simmr",build_vignettes=TRUE) 
library(simmr)
install_github("andrewljackson/SIBER", build_vignettes = TRUE) 
library(SIBER)
install_github("TGuillerme/mulTree@release")
install_github("healyke/SIDER", build_vignettes = TRUE) 
library(SIDER)
```

These will install the most up to date versions of the packages. You might run into the following problems:

  - If you are on a Mac you might need to install X11 from [http://www.xquartz.org](http://www.xquartz.org). 
  - You may get a pop up window be asking if you want 'additional build tools'. Please select 'yes'.
  - If you get an error about package `stringi` try typing `install.packages('stringi',type='win.binary')` if on Windows or `install.packages('stringi',type='mac.binary')` if on Mac. Then re-run the commands above
  - If you get some errors about `pandoc` when installing simmr leave out the `build_vignettes=TRUE` argument

### Step 3

MixSIAR should be installed by following the instructions here: [https://github.com/brianstock/MixSIAR](https://github.com/brianstock/MixSIAR). Make sure to follow the instruction for the full installation with the GUI, as we will be using this to teach MixSIAR. If you run into problems just install the standard version.
 
### Step 4
 
Finally if you would like to do some pre-course reading (recommended) there are some papers which can be accessed [here](https://github.com/andrewcparnell/simms_course/tree/master/papers).

Note: this might take a while as these are pretty big and complicated packages.

### Troubleshooting

If you run into any problems please drop us a line at <andrew.parnell@ucd.ie> (for SIAR/simmr/MixSIAR queries) or <andrew.jackson@tcd.ie> (for SIBER/SIDER queries).

