---
title: "Introduction to SIBER"
author: "Andrew L Jackson"
date: "July 10, 2015"
output: html_document
---

SIBER is subset of functions within the SIAR package and allow for analysis of analysis of data in isotope-space as opposed to diet-space such as in the mixing model side of siar. The SIBER functions and routines are currently obtainable within the R package siar, although work is underway to move them to their own standalone, but compatible package.

SIBER provides methods for comparing variation in isotope-space (d-space), which is commonly used as a proxy for niche width (both dietary and environmental) of the organisms. From the outset, it is important that you decide whether you want to compare among populations of individuals, or among communities comprising multiple populations.This distinction is discussed in a [video podcast](http://www.tcd.ie/Zoology/research/research/theoretical/Rpodcastsfiles/siber/siber_intro.mp4).

One of the difficulties is that when they were first introduced, the same convex hull based method was used for both types of comparisons ([Layman et al 2007](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=6yV_oeoAAAAJ&citation_for_view=6yV_oeoAAAAJ:u-x6o8ySG0sC) and [Layman et al 2007](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=6yV_oeoAAAAJ&citation_for_view=6yV_oeoAAAAJ:9yKSN-GCB0IC)). However, the paper introducing [SIBER ](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=E0sB7fUAAAAJ&citation_for_view=E0sB7fUAAAAJ:_FxGoFyzp5QC) showed clearly that ellipse-based approaches for describing isotopic niche widths of single popluations of individuals is far more statistically robust than the hull-based methods; and further introduced Bayesian methods for putting statistical error around the previously point-estimate hull-based metrics and thereby allowing quantiative comparisons to made between them.

Consider the following two figures:

```{r, echo=FALSE, message = FALSE, fig.width = 10, fig.height = 4}

library(siar, quietly = TRUE,
        verbose = FALSE,
        logical.return = FALSE)


par(mfrow=c(1,3))

source("plot.siber.data.r")

M <- plot.siber.data("../siber-scripts/example_layman_data.csv",
                tt = "Community 1", 
                xlim=c(-10, 15), 
                ylim=c(-5, 15))
M <- plot.siber.data("../siber-scripts/example_layman_data_2.csv",
                tt = "Community 2",
                xlim=c(-10, 15), 
                ylim=c(-5, 15))


# create a blank plot to house the legend
plot(0, type = "n", bty = "n", xaxt = "n", yaxt = "n",
     xlab = "", ylab = "")

legend("center",
       legend = as.character(c(paste("Group ",1:M),
                               "Convex hull \n through means")),
       pch = c(rep(1,M),NA),
       col=c(1:M,1,1),
       lty = c(rep(NA,M),1),
       bty="n",
       cex = 1.4)

```

Here we have two ecological communities, each comprising 4 groups or populations of individuals. There are 3 main comparisons, or questions of ecological relevance that we might ask of these data:

1. Within __Community 1__, do _Groups 1 to 4_ have the same isotopic niche and/or niche widths?
2. How does the isotopic niche width of the population described by _Group 1_ (which might be the same species) differ between __Community 1__ and __Community 2__?
3. How does the isotopic niche width of __Community 1__ differ to __Community 2__? 


## Comparisons between populations (options 1 and 2)
If you want to make comparisons between populations of individuals as was introduced by [Layman et al 2007](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=6yV_oeoAAAAJ&citation_for_view=6yV_oeoAAAAJ:9yKSN-GCB0IC) then you should only be thinking about comparing ellipses fitted to each population. In this situation, although you can calculate the other 6 "Layman metrics", they suffer from:

* only being point estimates with no statistical error and therefore you cannot compare two or more in a pairwise sense
* the convex hull metric shows very strong bias with sample size, since a hull can only get larger with additoinal data points and not smaller.

The construction of ellipses around the data by fitting [multivariate normal distributions](https://en.wikipedia.org/wiki/Multivariate_normal_distribution) to each population (group) using Bayesian Inference means that uncertainty in both the location (means) and size (covariance matrix) of the ellipse based on the samples can be estimated. With access to this uncertainty, one is then in a position to make robust statistical comparisons between two or more distributions of ellipses associated with each group. Furthermore, the results from the [SIBER paper](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=E0sB7fUAAAAJ&citation_for_view=E0sB7fUAAAAJ:_FxGoFyzp5QC) show clearly that these estimates are not biased with sample size of the population.

This approach is explored in more detail later on in this course under the topic __Ellipse based comparisons in SIBER__ (NB NEEDS LINK).

## Comparisons between communities comprised of multiple populations (option 3)

When you want to compare two communities, then the hull-based metrics from the original paper by [Layman et al 2007](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=6yV_oeoAAAAJ&citation_for_view=6yV_oeoAAAAJ:u-x6o8ySG0sC) are still appropriate. In this case, we can extend this method by fitting multivariate normal distributions to each population member of the community and thereby calculate the convex hull and other metrics based on the means of each of the populations (groups). With this statistical error in hand, we can then make robust probabalistic comparisons of the metrics between the  two (or more) communities. In more detail, the 6 metrics originally proposed by Layman et al 2007, and implemented in SIBER are:

* __TA__ - the area of convex hull containing, in the case of SIBER, the means of the populations that comprise the community.
* __dN_range__ - the distance in units between the min and max y-axis populations means which is most often d15Nitrogen in ecological studies.
* __dC_range__ - the distance in units between the min and max x-axis population means which is most often d13Carbon in ecological studies.
* __CD__ - the mean distance to centroid from the means
* __MNND__ - the mean nearest neighbour distance of the means
* __SDNND__ - the standard deviation of the nearest neighbour distance

This approach is explored in more detail later on in this course under the topic __Convex Hull based comparisons in SIBER__ (NB NEEDS LINK).





