---
title: "First-practical"
author: "Andrew L Jackson"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_notebook
---

## R revision

Download my [teaching files](https://github.com/adzidic/R_lectures) as a zip. In the folder `/podcasts` you can find some basic example R script files to practice and remind yourself how R works. At home you can follow my [video podcast](https://www.youtube.com/playlist?list=PLXXzyqr0tEhPRNDuEQ6wcvMcpAkGRjVqs) instructions that go with these, but they are large files and wont load from here, and besides, you have us in person for this course!


### Graphics
In the folder `/podcasts/graphs/`

- `basic_summary_statistics.r`
- `histograms_template.r`
- `boxplots_template.r`
- `boxplots_template.r`
- `scatter_plots_template.r`

### Basic linear models
In the folders `/podcasts/basic-analyses/` and `/podcasts/genearlised-linear-models/`
- `t_tests_example.r`
- `linear_regression_template.r`
- `binary_regression_template.r` 

----

## Run basic SIMM in JAGS

Turning now to Andrew Parnell's files in his folder of content you downloaded:

- copy R code from
  - `library(rjags)`
  - `library(siar)`
  - lines 194 to 211 in `/ap_notes/reg_and_simms.Rmd`
  - lines 155 - 166
- run the model and explore the posterior samples
- check for convergence
- check for autocorrelation in the posterior
- assess incluence of priors on the output


 
